### ISSUE TITLE
何时能开放代码呢?

### ISSUE THREAD

**Issue by chai2010** [qiniu/qlang#1]
内核居然只有1k行, 语言特性也很有意思.
请问许大何时可以开放代码呢?

感谢分享.

**Comment by longbai** [comment]
这些代码 已经开放了啊，您是要什么代码？

**Comment by chai2010** [comment]
想看下Go实现的那部分代码.

**Comment by longbai** [comment]
。。。 基本是和qnlang一样的

**Comment by chai2010** [comment]
怎么就关闭了, 是不会开放 Go 代码的意思吗

**Comment by xushiwei** [comment]
@chai2010 肯定会开放，只是目前还没具体的时间表。

**Comment by ailncode** [comment]
感谢分享
Good,可惜了还没开源
+32赞
学习...
