### ISSUE TITLE
Go包导入的具体规则是什么？

### ISSUE THREAD

**Issue by visualfc** [qiniu/qlang#108]
参考qlang的标准导入库描述Go包导入的规则以供qexport之类工具使用，请检查是否正确。

* 结构和函数
struct 类型：大写导出，以qlang.NewType的方式导出
NewStruct 函数：小写导出，并以struct名称导出
其他生成Struct函数：小写导出
其他函数：小写导出

* 变量
结构变量：大写导出，转换为指针
结构指针变量：大写导出
const变量: 小写导出

* 小写导出规则
如只有首字母为大写，则首字母小写导出，如开头两字母大写，则保持大写导出

* 疑问？
对于image.RGBA这种本身大写的类按以上规则会出现冲突，该如何定义？
"RGBA",qlang.NewType(reflect.TypeOf((*image.RGBA)(nil)).Elem())
"RGAB",image.NewRGBA

**Comment by xushiwei** [comment]
* 变量都大写导出
* image.NewRGBA 这种可以导出为 "rgba"，或者用 qlang.NewTypeEx 来消除冲突，这两种都可以。
