### ISSUE TITLE
一个建议

### ISSUE THREAD

**Issue by scp1513** [qiniu/qlang#121]
我喜欢go语言是因为他的简单和强类型，虽然qlang能和go很好兼容，但是脚本本身貌似就没有了强类型的优势。
其实可以想typescript编译成js一样，直接做一个golang编译成qlang的编译器。这样估计简单的多

**Comment by xushiwei** [comment]
这个我们确实有做这样的考虑。后续 qlang 会支持强类型，语法会更接近 golang，甚至可能完全兼容 go 语言。

**Comment by insionng** [comment]
@xushiwei   强烈建议兼容GO语法，因为目前的Qlang有些语法的表现形式还是有些别扭，还不如直接兼容Go语法更有优势，现在搞得似是而非，看起来好像很像，但细节又有不同，写的时候可能会比较迷惑。如果实在不是lua的几个go实现版本导出go函数到lua需要经过漫长的封装过程，估计选用lua这种语法简单的可能会更好。但是Qlang的优势就是导出go函数极其方便，唯一缺陷就是语法没有完美兼容go语法，搞得比较奇怪，看起来不怎么顺眼～

**Comment by xushiwei** [comment]
https://github.com/qiniu/qlang/issues/176

**Comment by rainydew** [comment]
灵活的类型和支持动态导入，可能会对自动化测试也更友好一些。之前go项目测试的时候，字段常改变，导致测试代码也跟着更改类型定义，会比较被动
我目前做测试开发大部分都是python，但是go的一些服务，sdk实现都只有go的。感觉看见之前qlang带来的灵活性，会考虑利用到自动化测试里去
