### ISSUE TITLE
可不可以做成类似otto那样，内嵌到Go语言里的脚本引擎？

### ISSUE THREAD

**Issue by yunyet** [qiniu/qlang#13]
如题，希望qlang能内嵌到Go语言里。
当然，这是建议，未必算是Issues.

我等小白伸手党，坐等 7牛 更多详细文档，包括使用方法。

**Comment by xushiwei** [comment]
当然可以啊，这个是主要目的

**Comment by yunyet** [comment]
不好意思，我又仔细看了一下 README.md。确实如楼上所说，是个好东东呢。
正是我项目中所需要的。和otto相比，QLang和Golang互操作的优点简直是有让人激动人心！
但是我等小白还是希望能又更详细的文档，或者视频。
比如，如何控制 脚本运行 timeout，这在otto里有vm.Interupt的chan的。
