### ISSUE TITLE
按照说明文档安装后，并不能直接在命令行使用 qlang

### ISSUE THREAD

**Issue by cloudtrends** [qiniu/qlang#130]
hi ,all

　　根据说明文档安装qlang到本地后，并没有生成 qlang  的命令二进制文件．

                go get -u -insecure qlang.io/qlang
　　
　　$qlang

               No command 'qlang' found,

应该还缺少一个生成 qlang cmd 的步骤吧？

谢谢

**Comment by xushiwei** [comment]
可以在 qlang 根目录下执行 make 来生成 qlang cmd。
后续我们完善下 README

**Comment by cloudtrends** [comment]
好的，多谢．

在　qlang.io 文件夹（也就是根目录）下面没有找到　Makefile  相关的内容，暂时还无法执行　make 命令．
