### ISSUE TITLE
多次include相对路径下文件时的问题

### ISSUE THREAD

**Issue by HuangDabao** [qiniu/qlang#134]
在/qlang/main.ql中include两个文件
include "a/b.ql"
include "x/y.ql"
结果是第一个include的是/qlang/a/b.ql，第二个include的是/qlang/a/x/y.ql，而不是/qlang/x/y.ql

**Comment by xujinzheng** [comment]
请问这个Bug有临时解决方案吗

**Comment by rainydew** [comment]
> 请问这个Bug有临时解决方案吗

include "../x/y.ql" 行不行
