### ISSUE TITLE
这样的场景能用qlang实现么

### ISSUE THREAD

**Issue by goddie1** [qiniu/qlang#139]
我们的场景有 点类似游戏，基本是功能基本明确，但是逻辑关系特别复杂多变，然后看到了qlang，想把功能实现还是放在go里面，用qlang动态处理逻辑代码，一次编译多次使用，不知道表述的有疑问么，

**Comment by goddie1** [comment]
在windows下面怎么debug qlang的代码，还是缺乏相关文档。。

**Comment by xushiwei** [comment]
可以用 qlang，这也是 qlang 的主要场景。
