### ISSUE TITLE
热更新代码疑问

### ISSUE THREAD

**Issue by qq358860528** [qiniu/qlang#140]
类似lua支持全局函数更新 元表函数更新
qlang的实现不知道怎么搞。
直接撸上有问题的代码
Foo = class {
	fn print() {
		//老版本代码
		println("ver1")
	}
}

foo = new Foo
foo.print() //ver1

Foo = class {
	fn print() {
		//替换新版本代码
		println("ver2")
	}
}
/*
//类似这样的写法也是不行的
Foo.print = fn(){println("ver2")}
*/

foo.print() //ver1 还是老代码

myprint = fn(){
	println("myprint ver1")
}

myprint() //myprint ver1 老版本
myprint = fn(){
	println("myprint ver2")
}
myprint() //myprint ver2 新版本

**Comment by qq358860528** [comment]
我在源码里面看到
class2_test.go
func TestInject
支持类动态添加类方法
有没有脚本级别支持动态添加修改支持?

**Comment by xushiwei** [comment]
https://github.com/qlangio/libs/blob/master/tricks/main_test.ql
