### ISSUE TITLE
能否或者如何实现其他语言的调用方案？

### ISSUE THREAD

**Issue by xuzhiping7** [qiniu/qlang#151]
就像目前各种语言都能通过三方库起调用LUA的形式~这样客户端和服务器很多逻辑代码都可以通用。

其实个人更看重golang的语法，如果客户端也能启用qlang的方案的话，那是在是大大的美好~

**Comment by szyhf** [comment]
附议

**Comment by xushiwei** [comment]
没打算支持其他语言

**Comment by szyhf** [comment]
@xushiwei 呃，可能是误会了，他想表达的是例如在移动端（iOS的环境）调用qlang的脚本执行命令，就像Readme.md中说的取代lua在游戏中的地位一样
