### ISSUE TITLE
强烈建议Q语言把Golang的热更新能力更新啊！

### ISSUE THREAD

**Issue by Think-Jumper** [qiniu/qlang#153]
强烈建议Q语言把Golang的热更新能力更新啊！虽然大家都在观望官方Go对热更新的后续支持是怎么样的，但是如果没什么特别情况，用带有强语法约束的脚本热更新将会是永恒不变的主题啊。建议七牛的大侠们现在就把这块完善，搭建起属于Golang自己使用的热更新体制吧，如果后期Golang的跨平台可以渗透到各种移动设备系统，那Q语言这个脚本发挥的作用应该可以达到或者更甚于Lua脚本对业界的影响了。

**Comment by listen-lavender** [comment]
顶

**Comment by gakaki** [comment]
支持
