### ISSUE TITLE
变量export似乎不太理想，实际值和qshell改变后的值对不上号

### ISSUE THREAD

**Issue by gpmn** [qiniu/qlang#164]
不好意思，我拿qshell弄了一个调试工具，但是发现export的变量，qshell中的值和实际的值似乎对不上。  

是我export变量的方法不对，还是qshell的export功能目前不能完美支持？  

谢谢指导！

**Comment by xushiwei** [comment]
有错误的样例么

**Comment by gpmn** [comment]
https://github.com/gpmn/goembed

我这里写了一个自己用的小工具，当时希望用来热调试程序，但是发现修改了变量不会实际修改成代码中的变量

**Comment by xushiwei** [comment]
看了你的样例，终于明白你说的 export 是什么意思了。目前来说，的确没有计划去支持将一个 Go 变量直接 export 给 qlang 代码。
