### ISSUE TITLE
无法获取结构字段

### ISSUE THREAD

**Issue by 456vv** [qiniu/qlang#169]
‘’‘

	net = R.PKG("net")
	fmt = R.PKG("fmt")
	
	broadcast = fn(){
	    netInterfaces, err = net.Interfaces()
	    if err != nil {
	    	return nil, err
	    }
	    for _, netInterface = range netInterfaces {
	    	println(netInterface.Name)
	    	//这里发生错误
	    	//type `net.Interface` doesn't has member `Name`
	    }
	    return nil, nil
	}
	
	main {
		
		bc, err = broadcast()
		if err != nil {
			W.WriteString(err.Error())
			return
		}
		W.WriteString(fmt.Sprint(bc))
		return
	}

‘’‘
把字段当成方法了，所以所以。难道七牛这个库自己都没在使用？

**Comment by xushiwei** [comment]
多谢反馈。上面是完整的代码么？

**Comment by 456vv** [comment]
这个库如果你们自己有在使用，这个错误是不应该出现的。判断：1)你们不使用。2)你们修改代码后出没有测试。

**Comment by aaple** [comment]
这个库感觉还在开发中吧  个人觉得 离能用还有点距离  加油吧 各位骚年
