### ISSUE TITLE
支持多线程重入吗？

### ISSUE THREAD

**Issue by bronzels** [qiniu/qlang#171]
你好，我把qlang用在爬虫colly上，colly的OnHTML回调是抽取内容的地方，这个函数我理解是被多线程的方式执行来加速爬取，在这里我用qlang来做每个网站不一样的一些计算处理。我发现如果OnHTML外面执行ql := qlang.New()，总是会出异常，但是如果我在OnHTML来调用ql := qlang.New()，就立刻没问题了？

**Comment by bronzels** [comment]
所以，我的问题是，咱们这个qlang，能不能主线程new一个vm，同一个vm用在多个线程中呢？

**Comment by xushiwei** [comment]
当前的样例代码比较简单。如果要高效，首先是把编译过程和执行过程分开，然后多个现程执行的时候，每个线程独立一个 Context。你可以稍微深入研究下代码。
