### ISSUE TITLE
支持多个协程共用一个 Qlang 对象吗？

### ISSUE THREAD

**Issue by dekunt** [qiniu/qlang#174]
使用 Qlang.Exec()  方法来编译一段代码的时候，发现在机器高负载的情况下执行比较慢（耗时达数秒），所以希望多个协程可以共用一个 Qlang 对象。
然而尝试之后发现，这样容易出现 exec.Function.Call()  方法返回各种错误: "invalid assignment statement", "variable assign without value"。

**Comment by xushiwei** [comment]
当前的样例代码比较简单。如果要高效，首先是把编译过程和执行过程分开，然后多个现程执行的时候，每个线程独立一个 Context。你可以稍微深入研究下代码。
