### ISSUE TITLE
怎么把变量从go传给qlang?

### ISSUE THREAD

**Issue by lx217197** [qiniu/qlang#175]
我已经知道go获取qlang是qlang.var,从qlang获取go呢？

**Comment by xushiwei** [comment]
直接传就可以，不需要转换。

**Comment by xushiwei** [comment]
在 Go 代码中把 foo 变量映射到 qlang 语言中： ql.SetVar("foo", foo)
这样在 qlang 代码中，就可以访问 foo 这个全局变量了。

**Comment by lx217197** [comment]
thank you,it's cool.
