### ISSUE TITLE
应该用什么ide去编写代码

### ISSUE THREAD

**Issue by a97077088** [qiniu/qlang#182]
应该用什么ide去编写代码

**Comment by xushiwei** [comment]
最新版本还只是preview版本，不适合正式基于它做。
老版本有一些社区贡献的 ide 插件：
* liteide - https://github.com/visualfc/liteide
* sublime - https://github.com/damonchen/sublime-qlang
* vim - https://github.com/simon-xia/vim-qlang
* atom - https://github.com/bingohuang/atom-language-q
