### ISSUE TITLE
proposal：将项目名称由qlang改为goscript

### ISSUE THREAD

**Issue by chenqinghe** [qiniu/qlang#194]
大佬好。

之前看到这个项目的时候，感觉非常好，很有前景。但是语法不兼容go语法，因此fork了本项目并创建goscript仓库：[https://github.com/goscript/goscript](https://github.com/goscript/goscript). 后来因为个人水平太菜等各种原因没能坚持下来，但是一直保持关注本项目。然后发现大佬有兼容go语法的计划 #176 ，因此原本的goscript项目也没存在的必要了。

但是相比于qlang来说，goscript在推广方面可能更有优势，并且从名字上就可以直观的看出go和goscript的关系（当然不同于java和javascript的关系），因此建议项目是不是改为goscript更好一些。如果大佬愿意修改，我可以无条件让出goscript组织以及goscript.io域名。

当然，叫qlang可能有基于商业上或者其他方面的考量，如果大佬不愿意修改，那我也表示理解。希望自己以后能为项目做一些贡献~

**Comment by xushiwei** [comment]
不考虑调整。因为 qlang 虽然兼容 Go 语言，但是不会止步于 Go 语言。单纯纯粹从把 Go 从静态编译转动态执行的意义没那么大。我是希望 qlang 能够进入帮助 Go 语言进入新的领域。
