### ISSUE TITLE
import 关键字无法识别 $QLANG_PATH 

### ISSUE THREAD

**Issue by Focinfi** [qiniu/qlang#42]
1. import 无法识别  $QLANG_PATH，应该是个bug，[这里是不是应该加上对 $QLANG_PATH 的支持?](https://github.com/qiniu/qlang/blob/develop/qlang.v2/module2.go#L36)

2. import 成功后（修改了 1. 链接处的代码），无法识别 new module.Class() 语法：
```
// $QLANG_PATH/types/main.ql
Slice = class {}
export Slice

// $$QLANG_PATH/play.ql
import "types"
slice = new types.Slice("int")

// 报错：
2016/04/18 18:26:23 line 2: match failed: `.Slice("int")
println(slice)` doesn't match `EOF`
panic: line 2: match failed: `.Slice("int")
println(slice)` doesn't match `EOF`
```

**Comment by xushiwei** [comment]
1. 这个要求在 main 中自己调用 SetLibs，参考 https://github.com/qiniu/qlang/blob/develop/app/qlang/main.go#L34

2. 这个确实是 bug，没有考虑支持 new module.Class

**Comment by xushiwei** [comment]
bug fixed
