### ISSUE TITLE
qexport 自动导出工具

### ISSUE THREAD

**Issue by visualfc** [qiniu/qlang#67]
我写了一个go package自动导出qlang模块的工具，目前使用go tool api进行导出标准包，但如果以后改用gotools的api则可以导出所有包https://github.com/visualfc/gotools/tree/master/goapi

因为是自动导出，所以导出规则仍不完善，与qlang自带的包不太一致。

https://github.com/visualfc/qexport

Examples:

		export sync
		> qexport sync

		export html and html/template package
		> qexport html html/template
	
		export all package
		> qexport std

**Comment by xushiwei** [comment]
提个pr吧，方便大家用qlang时给自己的package生成qlang module

**Comment by visualfc** [comment]
现在用的是go tool api只能导标准包，我看看能否将gotools的goapi包重构来提供api导出，如果直接用ast来做也不难，但go有一些os arch 相关函数/常量处理起来比较麻烦。
