### ISSUE TITLE
通过反射取得符号的godoc

### ISSUE THREAD

**Issue by xushiwei** [qiniu/qlang#71]
基本思路是通过符号值的go类型，取得对应的godoc，提供给 qlang shell 或者未来的 qlang ide。

**Comment by visualfc** [comment]
使用qlang导入的Go包缺少元数据，使用包导入后无法获取包的原始导入类似。
比如 qlang.Import("sys", syscall.Exports)，导入后sys只是一个map，没有原始go原始包syscall的信息存在，Go语言在这方面缺失，qlang应该支持以便于获取元数据，只需要一个原始id - syscall 即可。
```
type(sys)
> map[string]interface {}
```

**Comment by xushiwei** [comment]
```
$ qlang
Q-language - http://qlang.io, version qlang-develop darwin/amd64
Copyright (C) 2015 Qiniu.com - Shanghai Qiniu Information Technologies Co., Ltd.

qlang> ioutil._name
=> io/ioutil
```
