### ISSUE TITLE
qexport 增强建议：更智能的 NewXXX

### ISSUE THREAD

**Issue by xushiwei** [qiniu/qlang#77]
有些类虽然没有 NewXXX 创建函数，但是有其他初始化函数，那么不必自动添加 new 函数。例如 runtime 包 的 runtime.Func 类，虽然它没有 runtime.NewFunc，但是有 runtime.FuncForPC 可以创建 *runtime.Func，则我们不必自动生成 NewFunc 导出函数（如果需要，用户可自行手工添加）。

**Comment by xushiwei** [comment]
另外，有少量情况下，我们要的不是 *Type 实例而是 []Type 实例。例如：runtime.BlockProfileRecord 类。当然甚至有时候我们会同时需要两者。我们需要按需生成 blockProfileRecord、blockProfileRecords 甚至可能同时生成两者。

**Comment by visualfc** [comment]
使用 go/ast go/doc 重新实现 qexport
https://github.com/qiniu/qlang/pull/80

**Comment by visualfc** [comment]
qlang 本身不支持引用符号 & *，这样导出Go函数在qlang中使用可能会受到限制。
