### ISSUE TITLE
建议支持引用符 & * 操作

### ISSUE THREAD

**Issue by visualfc** [qiniu/qlang#81]
Go本身的函数参数支持引用，建议qlang支持引用和解引用，以便更好的利用Go语言提供的库。
即 & 和 * 操作

**Comment by xushiwei** [comment]
处理方法：

* 支持自动将 *build.Context 转为 build.Context（如果输入类型要求）

这样，在 qlang 中：

* *build.Context 和 build.Context 表现上是无差异的；
* 如果 Go package 的 export 符号是变量，且为 struct 类型，则 qlang 中导出为 *struct，而不是原始类型。

如此就不需要支持 * 和 & 了。
