### ISSUE TITLE
Go包按值导出时无法调用函数

### ISSUE THREAD

**Issue by visualfc** [qiniu/qlang#85]
如下，按指针返回在qlang中可以调用函数，按值返回则无法调用。

```
"newContext":              newContext,
"varContext":               varContext,

func newContext() *build.Context {
	return new(build.Context)
}
func varContext() build.Context {
	var ctx build.Context
	return ctx
}
```

**Comment by xushiwei** [comment]
其实不是不支持，而是在输入类型为 build.Context，而函数的输入要求是 this *build.Context 时，自然找不到对应的 method。

处理方法：

* 支持自动将 *build.Context 转为 build.Context（如果输入类型要求），已经实现；

对 qexport 的建议：

* 如果一个 export 符号是变量，且为 struct 类型，则导出为 *struct，而不是原始类型。
